branches: 
  - master
  - main
preset: angular
repositoryUrl: https://github.com/karlderkaefer/golang-example-project
plugins:
  - "@semantic-release/commit-analyzer"
  - - "@semantic-release/release-notes-generator"
    - preset: angular
      writerOpts:
        commitsSort: ["subject", "scope"]
  - "@semantic-release/git"
  - - "@semantic-release/exec"
    - publishCmd: |
        echo "${nextRelease.notes}" > /tmp/release-notes.md
        goreleaser release --release-notes /tmp/release-notes.md --clean
