branches: 
  - master
  - main
preset: angular
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/git"
  - - "@semantic-release/exec"
    - publishCmd: |
        goreleaser release --clean
