name: release

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:

permissions:
    contents: read

jobs:
  generate-changelog:
    # run only on tag events
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate Changelog
      uses: docker://githubchangeloggenerator/github-changelog-generator:v1.16.4
      env:
        CHANGELOG_GITHUB_TOKEN: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
      with:
        args: --user ${GITHUB_REPOSITORY%/*} --project ${GITHUB_REPOSITORY#*/}
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
        contents: write # to be able to publish a GitHub release
        issues: write # to be able to comment on released issues
        id-token: write # needed for keyless signing
        pull-requests: write # to be able to comment on released pull requests
        packages: write # needed for ghcr access
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
            install-only: true
      - name: Show GoReleaser version
        run: goreleaser -v
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/exec
