name: release

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  generate-changelog:
    # run only on tag events
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Generate Changelog
        uses: docker://orhunp/git-cliff:2.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
        with:
          args: --output docs/CHANGELOG.md
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "chore(docs): update changelog"
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      id-token: write # needed for keyless signing
      pull-requests: write # to be able to comment on released pull requests
      packages: write # needed for ghcr access
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
      - name: Show GoReleaser version
        run: goreleaser -v
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/exec
