name: release

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  generate-changelog:
    # run only on tag events
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: docs/CHANGELOG.md
      
      - name: Commit files
        id: commit
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            echo "hasdiff=false" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected."
            echo "hasdiff=true" >> "$GITHUB_OUTPUT"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add docs/CHANGELOG.md
            git commit -m "chore(docs): update changelog"
          fi
      - name: Push changes
        if: ${{ steps.commit.outputs.hasdiff == 'true' }}
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
  goreleaser:
    runs-on: ubuntu-latest
    needs:
      - generate-changelog
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      id-token: write # needed for keyless signing
      pull-requests: write # to be able to comment on released pull requests
      packages: write # needed for ghcr access
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
      - name: Show GoReleaser version
        run: goreleaser -v
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGELOG_GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/exec
  